apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: xxxx # 改成 minio 或者阿里云的 access id
  AWS_SECRET_ACCESS_KEY: xxxxx # 改成 minio 或者阿里云的 access key
  AWS_ENDPOINTS: https://oss-cn-shanghai.aliyuncs.com
  VIRTUAL_HOSTED_STYLE: "true" # 对于阿里云必须要新增，否则无法备份
